version: "3.9"

services:
  redis:
    container_name: redis
    image: redis:alpine3.17
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  postgres:
    container_name: postgres
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Postgres123
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    container_name: amazonabzar.pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    ports:
      - 7000:80
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=123456789
volumes:
  redis-data:
  postgres-data:
  pgadmin-data:
